#pragma once
#include <ntifs.h>

#define IOCTL_MAP_MEMORY   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNMAP_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define MAX_EVENT_MESSAGE 256
#define MAX_EVENTS 1024


typedef struct _MONITOR_EVENT {
    LARGE_INTEGER TimeStamp;
    WCHAR Message[MAX_EVENT_MESSAGE];
} MONITOR_EVENT, * PMONITOR_EVENT;

typedef struct _SHARED_MEMORY_BUFFER {
    volatile ULONG WriteIndex; // Драйвер пишет сюда
    volatile ULONG ReadIndex;  // User-Mode читает отсюда
    MONITOR_EVENT Events[MAX_EVENTS];
} SHARED_MEMORY_BUFFER, * PSHARED_MEMORY_BUFFER;